### ISSUE TITLE
Move images into a single directory

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-fusion#1]
In your app directory, move background.jpg, logo.png, and logo_without_name.png into a folder called "images". Don't clutter your app directory as it will contain your source codes.

**Comment by ssvillarosa** [comment]
Do not simply close a ticket without acknowledgement nor a proper response. I will re-open this ticket again and close it properly.

**Comment by Cayiee** [comment]
Dear Professor Villarosa,

Thank you for your instructions. I would like to inform you that we have promptly addressed the issue by moving background.jpg, logo.png, and logo_without_name.png into a designated folder named "images" within our app directory. This adjustment ensures a cleaner organization of files, separating visual assets from the source code.

Best regards,
Castillo, Krystel Caye R.
