### ISSUE TITLE
Database Schema Feedback

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-fusion#3]
Same with purchase order, you can also get rid of the delivery table. Once you receive the list of purchase order, you will also get the destination address and destination name. The source address and source name should come from the seller right? 
You have 3 options:
- In your seller table, add the seller address and name. When an item is paid and ready for shipping, the seller can start the delivery by simply calling the request-delivery() API providing the source from seller details and destination details from purchase order(buyer details).
- You can have a multiple address for the seller. You need to create another table for the seller's addresses. In that table is also the name for the source name(or the sender). When an item is paid and ready for shipping, the seller can start the delivery. First, the seller can choose the source address if the seller has multiple addresses or if there is only one, it is selected by default. The seller's selected address will become the source address and source name. The buyer's address and name from purchase order will become the destination address and destination name.
- If you want to add more challenge, you can implement it so that a seller can multiple sender and multiple addresses.

I also updated the customer get-purchase-orders() API so that it will cater your needs. Please see attached.
![customer update](https://github.com/PUP-BSIT/project-fusion/assets/76401444/b5b99599-c570-4023-a316-37b509fbeb4f)

Kindly note as well that I'm spoon feeding you with information. I'm expecting you to be more analytical so that we can discover the lapses in the requirement. This phase of development is crucial because many of your time and effort will go to waste if the fault in the design is discovered later on especially when you have already started the development. Be more proactive. Analyze, ask, and discuss. I will no longer point out the mistake in your design next time it happens. I will let you go far until you yourselves discover the mistake and realize how costly it was to make mistake in the design phase.

**Comment by Cayiee** [comment]
Dear Professor Villarosa,

I hope this message finds you well. I wanted to inform you that, after careful consideration, we've chosen option 1 for our project's design. We'll be enhancing the seller table with the seller's address, name, bank code, and account number. This additional information is crucial for seamless transactions, enabling us to provide the necessary details to the bank and logistics.

We appreciate your guidance and are committed to a proactive and analytical approach. 

Thank you for your continued support.

Best regards,
Castillo, Krystel Caye R.

**Comment by ssvillarosa** [comment]
I saw it coming that you will select the option with the least effort. It's fine and I understand your struggle with what we are doing. However, consider that this is a collaborative project with your DBMS subject. Based on the initial design, you will only have 2 tables in your application. The reason I gave you those options is for you to expand your database. If your database subject professor is fine with that 2 tables, then I'm also good with that. Once you have updated your design, you can close this ticket.

**Comment by ssvillarosa** [comment]
2 days has passed and no acknowledgement has been from your end. All members of Fusion group will be given 2 demerit points.

**Comment by Cayiee** [comment]
Dear Prof. Villarosa,

We've reached out to the Database Management professor for approval on our proposed database schema design immediately after your concern was raised. Unfortunately, we have not yet received acknowledgment.

Your understanding and timely feedback are crucial for the progression of our collaborative project. We remain committed to seeking approval and will promptly update the design upon confirmation.

Best regards,

Castillo, Krystel Caye R.

**Comment by Cayiee** [comment]
Dear Professor Villarosa,

I hope this email finds you well. I wanted to inform you that I have received feedback from Ma'am Nikki Dela Rosa regarding our Database Design.

Ma'am Dela Rosa has suggested incorporating additional tables to enhance the representation of relationships discussed in class. She mentioned that even if these tables may not be directly utilized in the application, their inclusion would provide a more comprehensive view of the discussed relationships.

After considering Ma'am Dela Rosa's suggestions, we have decided to proceed with the original plan of using two tables for the database. However, to address Ma'am Dela Rosa's valuable input, we will also create an additional database design that includes the additional tables.

Thank you for your understanding, and I appreciate your guidance on this matter.

Best Regards, 
Castillo, Krystel Caye R.

**Comment by ssvillarosa** [comment]
Hi Ms. Castillo and to everyone in this group,

First thing, I can't help but to express my disappointment that you chose the easiest part. I have lots of ideas and improvements for this app such as categorization of products, multiple seller addresses, etc. I had to lower the bar just to match your capabilities. Upon checking your exercises and performance, I understand that you were struggling to catch up with our lessons. It also saddens me that your group is the least active in terms of code commits here in Github for the past few weeks. I also had to gave you demerit points just so you become responsive. I honestly don't feel your interest in my subjects and it seems like you were giving me a bare minimum. You gave me a database design that seemed like you didn't analyze the requirements fully. Then you choose the option with the least effort when I gave you some options to expand it.

Understand this. In our first meeting, I told you that our subject will not be fun. It will be boring. I told you that it won't be easy. And the sad thing is, this will be your life once you graduated and make it to the industry. Even if I let you pass now, you will still have this struggle only in different form. When you're there, I will no longer be your teacher. Life itself will teach you and it's much worse than I do.

We are now in the middle of the development but it's never too late for you. I'm hoping you would reconsider these. I know you can do better than this.

You may now close this ticket.

**Comment by Cayiee** [comment]
Dear Prof. Villarosa,

I appreciate your feedback and understand the concerns you raised. We apologize for falling short of expectations. We are committed to reevaluating our project choices and assure you that we will reconsider the selected option.

Thank you for your understanding.

Best Regards,
Castillo, Krystel Caye R.
